app = "student-app-001"
primary_region = "fra"

[build]
  builder = "docker"

[env]
  PORT = "8080"
  FLASK_SECRET_KEY = "x7k9m2p8q5w3z1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[mounts]]
  source = "data"
  destination = "/data"
